// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW98OM0h-PoNx4zy9l2_vf5r0mAydVuzE',
    appId: '1:874148534600:web:2605035a30b8f98173fb7d',
    messagingSenderId: '874148534600',
    projectId: 'hajeri-8c539',
    authDomain: 'hajeri-8c539.firebaseapp.com',
    storageBucket: 'hajeri-8c539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeB_jWeMTvdxdTp1LLp5y72JuhCN6hE-U',
    appId: '1:874148534600:android:74e1044321395f3d73fb7d',
    messagingSenderId: '874148534600',
    projectId: 'hajeri-8c539',
    storageBucket: 'hajeri-8c539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWo-MghEykx7XvMciaQhuUk2lQ-_9WlU',
    appId: '1:874148534600:ios:2cc56729f5d55b9273fb7d',
    messagingSenderId: '874148534600',
    projectId: 'hajeri-8c539',
    storageBucket: 'hajeri-8c539.appspot.com',
    iosBundleId: 'com.example.hajeri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtWo-MghEykx7XvMciaQhuUk2lQ-_9WlU',
    appId: '1:874148534600:ios:2cc56729f5d55b9273fb7d',
    messagingSenderId: '874148534600',
    projectId: 'hajeri-8c539',
    storageBucket: 'hajeri-8c539.appspot.com',
    iosBundleId: 'com.example.hajeri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW98OM0h-PoNx4zy9l2_vf5r0mAydVuzE',
    appId: '1:874148534600:web:2ec14ca0b981b19773fb7d',
    messagingSenderId: '874148534600',
    projectId: 'hajeri-8c539',
    authDomain: 'hajeri-8c539.firebaseapp.com',
    storageBucket: 'hajeri-8c539.appspot.com',
  );
}
